### ISSUE TITLE
提示

### ISSUE THREAD

**Issue by jaxsohu** [ZhouMoon/ZhouMoon.github.io#1]
你的github账号ZhouMoon，在gitstar.com.cn上设置了目标仓库ZhouMoon/ZhouMoon.github.io，目前你的欠赞数量过多，请尽快回赞，否则将被加入黑名单，所有获赞将取消。
如想停止互赞，请在不欠赞的情况下关闭互赞开关，就不会有人再给你点赞了，请知悉，谢谢。

**Comment by ZhouMoon** [comment]
已回
